server:
  port: 9011
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:
      default Zone: http://127.0.0.1:6868/eureka
    instance:
      prefer-ip-address: true
