server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.169.128:3306/tensquare_base?characterEncoding=utf-8
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      default Zone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true