server:
  port: 9010
spring:
  application:
    name: tensuqare-friend
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.169.128:3306/tensquare_friend?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
jwt:
  config:
    key: zdw1213
    ttl: 3600000
eureka:
  client:
    service-url:
      default Zone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true